name: Run clippy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings" # Make sure CI fails on all warnings

jobs:
  CI:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy
