name: Check Formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get newest stable
        run: rustup update stable && rustup default stable

      - name: Use cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check
