name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test

      - name: Run tests with msb-spi feature
        run: cargo test --features msb-spi
